name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 在 runner 上建立 .env 檔，內容來自 Repository Secrets
      - name: Create .env file
        run: |
          echo "REACT_APP_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "REACT_APP_API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
